name: "FerretDB in GitHub Actions"
description: "Start a FerretDB instance"

branding:
  icon: "database"
  color: "blue"

inputs:
  ferretdb-version:
    description: 'FerretDB version to use (default "latest")'
    required: false
    default: "latest"

  ferretdb-port:
    description: "FerretDB port to use (default 27017)"
    required: false
    default: "27017"

  ferretdb-telemetry:
    description: 'Configure FerretDB telemetry (default "disabled")'
    required: false
    default: "disabled"

  use-postgres:
    description: 'Configure FerretDB to use PostgreSQL (default "disabled")'
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ferretdb-version }}
    - ${{ inputs.ferretdb-port }}
    - ${{ inputs.ferretdb-telemetry }}
    - ${{ inputs.use-postgres }}
